version: '3.4'
services:
  db:
    image: kleitonarufino/mysql-rest-with-spring-boot-docker
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_docker
    ports:
      - "3308:3306"
    networks:
      - docker-network
  rest-with-spring-boot-docker:
    image: kleitonarufino/rest-with-spring-boot-docker
    restart: always
    build: ./apirest_springboot
    working_dir: /apirest_springboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./apirest_springboot:/apirest_springboot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - docker-network
networks:
    docker-network:
        driver: bridge