version: '3.4'

services:  
  api-rest-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: api_rest_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - mynet-network
  
  api-rest:
    image: kleitonarufino/api-rest
    restart: always
    build:
      context: .
      dockerfile: api-rest/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://api-rest-db:3308/api_rest_db?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8080:8080
    depends_on:
      - api-rest-db
    networks:
      - mynet-network  
      
networks:
   mynet-network:
     driver: bridge